apps/blog/urls.py
from django.conf.urls import include, url
from apps.blog import views as blog_views

urlpatterns = [
	url(r'^blog/$', blog_views.home_blog
		, name='home_blog'),

	url(r'^blog/post/(?P<slug>[-\w]+)/$', blog_views.PostDetailView.as_view()
    	, name='detalle_post'),

	url(r'^blog/tutorial/(?P<slug>[-\w]+)/$', blog_views.TutorialDetailView.as_view()
    	, name='detalle_tutorial'),
	url(r'^panel/blog/crear-post/$', blog_views.crear_post.as_view(), name='crear_post'),
    url(r'^panel/blog/gestion-categorias/$', blog_views.gestion_categorias, name='gestion_categorias'),
    url(r'^panel/blog/gestion-categorias/editar/(?P<pk>\d+)/$', blog_views.CategoriaUpdateView.as_view(), name='editar_cat'),
    url(r'^panel/blog/gestion-categorias/borrar/(?P<pk>\d+)/$', blog_views.CategoriaDeleteView.as_view(), name='delete_cat'),
    url(r'^panel/blog/ver-posts/$', blog_views.ver_posts, name='ver_posts'),
    url(r'^panel/blog/editar-post/(?P<pk>\d+)/$', blog_views.PostUpdateView.as_view(), name='editar_post'),
    url(r'^panel/blog/borrar-post/(?P<pk>\d+)/$', blog_views.PostDeleteView.as_view(), name='delete_post'),
    url(r'^blog/categoria/(?P<slug>[-\w]+)/$' ,blog_views.CategoriaView.as_view(), name = 'categoria-blog'),
    url(r'^registrar-suscriptor/$', blog_views.registrar_suscriptor, name='registrar_susciptor'),
	
	
  
]

tecnix/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from apps.home import reset_password_views as recovery_pass
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls')),
    url(r'^', include('apps.tecnicos.urls')),
    url(r'^', include('apps.api.urls')),
    url(r'^', include('password_reset.urls')),
    url(r'^chaining/', include('apps.smart_selects.urls')),
    url(r'^password_reset/$'
    	, recovery_pass.ResetPasswordRequestView.as_view()
    	, name='reset_password'),

    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$'
    	, recovery_pass.PasswordResetConfirmView.as_view()
    	,name='reset_password_confirm'),
    
    url(r'^password_reset/enviado/$'
    	, auth_views.password_reset_done
    	, name='password_reset_done'),


    url(r'^password_reset/confirm/terminado/$'
    	,auth_views.password_reset_complete
    	, name='password_reset_complete'),

    
]

apps/blog/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible


class TimeStampModel(models.Model):

	user = models.ForeignKey(User, db_index=True, null=True, blank=True)
	description = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	modified = models.DateTimeField(auto_now = True)

	class Meta:
		abstract = True 

@python_2_unicode_compatible
class Categoria(models.Model):

	nombre = models.CharField(max_length=40)
	slug = models.SlugField(editable = False, unique=True, null=True, blank=True, max_length=255)

	def __str__(self):
		return "{0}".format(self.nombre)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.nombre)
		super(Categoria, self).save(*args,**kwargs)
		
def upload_imagen_to(instance, filename):
    import os
    from django.utils.timezone import now
    filename_base, filename_ext = os.path.splitext(filename)
    return 'noticias/%s%s' % (
        now().strftime("%Y%m%d%H%M%S"),
        filename_ext.lower(),
    )
@python_2_unicode_compatible
class Noticia(TimeStampModel):

	imagen = models.ImageField(upload_to=upload_imagen_to, blank=True)
	titulo = models.CharField(max_length=400, editable = True)
	categoria = models.ManyToManyField(Categoria)
	slug = models.SlugField(editable = True, unique=True, null=True, blank=True,max_length=400)
	vistas = models.BigIntegerField(default=0)
	def save(self, *args, **kwargs):
		self.slug = slugify(self.titulo)
		super(Noticia, self).save(*args,**kwargs)

	def __str__(self):
		return "{0}".format(self.titulo)




class Answer(models.Model):

	user = models.CharField(max_length=500, blank=False)
	description = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	noticia = models.ForeignKey(Noticia)

	def __str__(self):
		return "{0}".format(self.user)

def upload_imagen_tuto(instance, filename):
    import os
    from django.utils.timezone import now
    filename_base, filename_ext = os.path.splitext(filename)
    return 'tutoriales/%s%s' % (
        now().strftime("%Y%m%d%H%M%S"),
        filename_ext.lower(),
    )

@python_2_unicode_compatible
class Tutorial(TimeStampModel):

	imagen = models.ImageField(upload_to=upload_imagen_tuto, blank=True)
	titulo = models.CharField(max_length=400, editable = True)
	categoria = models.ManyToManyField(Categoria)
	slug = models.SlugField(editable = True, unique=True
		, null=True, blank=True,max_length=400)
	video_id = models.CharField(max_length=50, editable = True, blank=True)
	vistas = models.BigIntegerField(default=0)


	def save(self, *args, **kwargs):
		self.slug = slugify(self.titulo)
		super(Tutorial, self).save(*args,**kwargs)

	def __str__(self):
		return "{0}".format(self.titulo)

class Calificacion_tuto(models.Model):
	usuario =  models.CharField(max_length=500, blank=False)
	tutorial = models.ForeignKey(Tutorial)
	fecha = models.DateTimeField(auto_now_add=True)
	puntuacion = models.IntegerField(default=1)
	comentario = models.TextField(blank=True)

	def __str__(self): 
		return "{0} - {1} - {2}".format(self.puntuacion,self.tutorial,self.usuario)

apps/blog/forms.py
from __future__ import unicode_literals
from django.forms import ModelForm
from django import forms
from .models import Categoria, Noticia, Answer


class NuevoPostForm(forms.ModelForm):
	
	class Meta:
		model = Noticia
		exclude = ('created','modified','user','slug','vistas')

	def __init__(self, *args, **kwargs):
		super(NuevoPostForm, self).__init__(*args, **kwargs)

class EditPostForm(forms.ModelForm):
	
	class Meta:
		model = Noticia
		exclude = ('created','modified','user','slug','vistas')

	def __init__(self, *args, **kwargs):
		super(EditPostForm, self).__init__(*args, **kwargs)


class NuevaCategoriaForm(forms.ModelForm):
	
	class Meta:
		model = Categoria
		exclude = ('slug',)

class EditCategoriaForm(forms.ModelForm):
	
	class Meta:
		model = Categoria
		exclude = ('slug',)

apps/blog/views.py
from django.shortcuts import render
from .models import Categoria, Noticia, Answer, Tutorial, Calificacion_tuto
from django.views.generic import ListView, CreateView, DetailView
from tecnix.estandar.view import InstanceMixin, LoginMixin
from .forms import NuevoPostForm, NuevaCategoriaForm, EditCategoriaForm, EditPostForm
from apps.home.models import Suscriptor
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
try:
    from django.utils import simplejson as json
except ImportError:
    import json
 

def home_blog(request):
    tutos = Tutorial.objects.all()
    categs = Categoria.objects.all()
    noticias = Noticia.objects.all()

    return render(request,'blog/index.html',{'noticias':noticias
		,'tutos':tutos,'categs':categs})

@require_POST 
def registrar_suscriptor(request):
    form = Suscriptor()
    if request.method == 'POST':
        items = request.POST.get('suscriptor_dict', None)
        items = str(items).split("/")

        for i in range(0, len(items)):
            item = json.loads(items[i])
            nombre = item['nombre']
            email = item['email']
        form.nombre = nombre
        form.email = email
        form.save()
        message = 'Su solicitud se ha registrado! Gracias por suscribirte.'
        ctx = {'message': message}
    # use mimetype instead of content_type if django < 5
    return HttpResponse(json.dumps(ctx), content_type='application/json')


class PostDetailView(DetailView):

    model = Noticia
    context_object_name = 'noticia'
    template_name ='blog/publicacion.html'

    def get_answers(self, noticia):
        answers = Answer.objects.filter(noticia = noticia).order_by('-created')

        noticia1 = Noticia.objects.get(slug = noticia.slug)
        noticia1.vistas += 1
        noticia1.save()
        return answers

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['answers'] = self.get_answers(context['object'])
        context['noticias'] = Noticia.objects.all().order_by('-created')[:6]
        context['categorias'] = Categoria.objects.all().order_by('-nombre')
        
        return context

    def post(self, request, *args, **kwargs):
        answer = Answer()
        answer.user = request.POST['user']
        answer.description = request.POST['description']
        answer.noticia = Noticia.objects.get(slug = kwargs['slug'])
        answer.save()
        answers = self.get_answers(answer.noticia)
        return render(request, 'blog/publicacion.html', 
                        {'noticia' : answer.noticia , 'answers':answers})

        
class TutorialDetailView(DetailView):

    model = Tutorial
    context_object_name = 'tutorial'
    template_name ='blog/detalle-tutorial.html'

    def get_Calificacion_tuto(self, tutorial):
        calificaciones = Calificacion_tuto.objects.filter(tutorial = tutorial).order_by('-fecha')

        tutorial1 = Tutorial.objects.get(slug = tutorial.slug)
        tutorial1.vistas = tutorial1.vistas + 1
        tutorial1.save()
        print("sumé 1")
        return calificaciones

    def get_context_data(self, *args, **kwargs):
        context = super(TutorialDetailView, self).get_context_data(**kwargs)
        context['calificaciones'] = self.get_Calificacion_tuto(context['object'])
        context['tutoriales'] = Tutorial.objects.all().order_by('-created')[:6]
        context['categorias'] = Categoria.objects.all().order_by('-nombre')

        califiaciones2 = self.get_Calificacion_tuto(context['object'])
        suma = 0
        if califiaciones2:
        	for x in califiaciones2:
        		suma += x.puntuacion
        	context['calificacion_total'] = suma / califiaciones2.count()
        else:
        	context['calificacion_total'] = 0
        
        return context

    def post(self, request, *args, **kwargs):
        calificacion = Calificacion_tuto()
        if request.user.is_authenticated():
        	calificacion.usuario = request.user
        else:
        	calificacion.usuario = request.POST['user']
        
        calificacion.comentario = request.POST['description']
        calificacion.puntuacion = request.POST['calificacion']
        calificacion.tutorial = Tutorial.objects.get(slug = kwargs['slug'])
        calificacion.save()
        calificaciones = Calificacion_tuto.objects.filter(tutorial=calificacion.tutorial)

        suma = 0
        for x in calificaciones:
        	suma += x.puntuacion

        calificacion_total = suma / calificaciones.count()

        tutoriales = Tutorial.objects.all().order_by('-created')[:6]

        return render(request, 'blog/detalle-tutorial.html', 
                        {'tutorial' : calificacion.tutorial
                        , 'calificaciones':calificaciones
                        ,'calificacion_total':calificacion_total
                        ,'tutoriales':tutoriales})

class crear_post(CreateView, InstanceMixin,LoginMixin):

    template_name = "blog/crear-post.html"
    model = Noticia
    form_class = NuevoPostForm
    success_url = reverse_lazy('ver_posts')

    def form_valid(self, form):
    	form.instance.user = self.request.user
    	return super(crear_post, self).form_valid(form)

    def form_invalid(self, form):
    	return super(crear_post, self).form_invalid(form)


@login_required
def gestion_categorias(request):

    form = NuevaCategoriaForm(request.POST or None)
    categorias = Categoria.objects.all().order_by('nombre')

    if form.is_valid():
        form.save()
        
        return HttpResponseRedirect(reverse('gestion_categorias'))

    return render (request,'blog/gestion-categorias.html',{'form':form,'categorias':categorias})

class CategoriaUpdateView(UpdateView, LoginMixin):
    template_name = "blog/edit-categoria.html"
    model = Categoria
    form_class = EditCategoriaForm

    def get_success_url(self, **kwargs):

        return reverse_lazy('gestion_categorias')

class CategoriaDeleteView(DeleteView, LoginMixin):

    template_name = "blog/delete-cat.html"
    model = Categoria
    success_url = reverse_lazy('gestion_categorias')

def ver_posts(request):
	posts = Noticia.objects.all().order_by('-created')
	return render (request,'blog/ver-noticias.html',{'posts':posts})

class PostUpdateView(UpdateView, LoginMixin):
    template_name = "blog/edit-post.html"
    model = Noticia
    form_class = EditPostForm

    def get_success_url(self, **kwargs):

        return reverse_lazy('ver_posts')

class PostDeleteView(DeleteView, LoginMixin):

    template_name = "blog/delete-post.html"
    model = Noticia
    success_url = reverse_lazy('ver_posts')

class CategoriaView(ListView):
    template_name ='blog/reviews.html'
    context_object_name = "list"
    paginate_by = '10'

    def get_queryset(self, *args, **kwargs):
        noticias = Noticia.objects.filter(categoria__slug=self.kwargs['slug']).order_by('-created')      
        return noticias

templates/blog/delete-post.html
{% extends 'app/panel.html'%}
 {% load staticfiles %}
 {% load widget_tweaks %}
 {% load blogtag %}
{% block tittle-view %}
<title>Borrar Post {{object.id}} | Coreducar</title>
{% endblock %}
{% block titulo-view%}
<h3>Borrar Post del blog</h3>	
{% endblock %}
{% block body-view%} <br><br><br>
	<div class="col-sm-12">
		<div class="row">
			<div class="panel panel-primary" data-collapsed="0">
				<div class="panel-heading">
					<div class="panel-title">
						Borrar Post ({{object.titulo}})
					</div>
					<div class="panel-options">
						<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
					</div>
				</div>
				<div class="panel-body">

					<form method="POST">{% csrf_token %}
                
                  <center>
                  <div class=" alert-danger col-md-6">

                  <h3>¿ Desea realmente eliminar el Post "{{object.titulo}}" con ({{object.answer_set|get_count_comentarios}}) Comentarios ?</h3>
                  
                  </div></center><br>
                  <div class="row col-md-12">
                  <center><br>
                  <input type="submit" class="btn btn-danger btn-flat btn-lg" value="Confirmar">
                  <a class="btn btn-info btn-flat btn-lg" href="{% url 'ver_posts' %}">Cancelar</a>
                  </form>
				</div>
			</div>
		</div>
		<link rel="stylesheet" href="{% static "Panel/css/font-icons/font-awesome/css/font-awesome.min.css"%}">

{% endblock %}

templates/blog/gestion-categorias.html
{% extends 'app/panel.html'%}
 {% load staticfiles %}
 {% load widget_tweaks %}
 {% load blogtag %}
{% block tittle-view %}
<title>Gestión Categorías | Coreducar</title>
{% endblock %}
{% block titulo-view%}
<h3>Gestionar Categorías del blog</h3>	
{% endblock %}
{% block body-view%} <br><br><br>
	<div class="col-sm-12">
		<div class="row">
			<div class="panel panel-primary" data-collapsed="0">
				<div class="panel-heading">
					<div class="panel-title">
						Nueva Categoría
					</div>
					<div class="panel-options">
						<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
					</div>
				</div>
				<div class="panel-body">

					<form role="form" method="POST" class="form-horizontal form-groups-bordered">
						{% csrf_token %}
						{% if form.errors %}
						<span class="alert-danger">{{form.errors}}</span>
						{% endif %}

						<div class="form-group">
							<label class="col-sm-3 control-label">Nombre de la Categoría</label>
							
							<div class="col-sm-5">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-tag"></i></span>
									{% render_field form.nombre class+="form-control" name+="nombre" placeholder="Escriba nombre aquí..."%}
								</div>
							</div>
						</div>
						<div class="text-center"><br>
							<button type="submit" class="btn btn-lg btn-blue center">Guargar</button>
						</div>
						
					</form>
				</div>
			</div>
		</div>
		<div class="col-sm-12">
			<div class="row">
				<div class="panel panel-primary" data-collapsed="0">
					
					<!-- panel head -->
					<div class="panel-heading">
						<div class="panel-title">Lista de Categorías Creadas</div>
						
						<div class="panel-options">
							
							<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
							
						</div>
					</div>
					
					<!-- panel body -->
					<div class="panel-body">
						
						<table class="table table-bordered table-hover datatable" id="table-1">
							<thead>
								<tr>
									<th>#</th>
									<th>Nombre</th>
									<th>Slug</th>
									<th>Noticias relacionadas a esta Categoría</th>
									<th>Opciones</th>
								</tr>
							</thead>
							<tbody>
								{% for categoria in categorias %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{categoria.nombre}}</td>
										<td>{{categoria.slug}}</td>
										<td>{{categoria.noticia_set|get_count_noticias}}</td>
										<td>
											<a href="/panel/blog/gestion-categorias/editar/{{categoria.id}}"><button class="btn">Editar</button></a>
											<a href="/panel/blog/gestion-categorias/borrar/{{categoria.id}}"><button class="btn">Borrar</button></a>
										</td>
									</tr>
								{% endfor %}
								
							</tbody>
							<tfoot>
								<tr>
									<th>#</th>
									<th>Nombre</th>
									<th>Slug</th>
									<th>Noticias relacionadas a esta Categoría</th>
									<th>Opciones</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	

<script type="text/javascript">
var responsiveHelper;
var breakpointDefinition = {
    tablet: 1024,
    phone : 480
};
var tableContainer;

	jQuery(document).ready(function($)
	{
		tableContainer = $("#table-1");
		
		tableContainer.dataTable({
			"sPaginationType": "bootstrap",
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
			"bStateSave": true,
			

		    // Responsive Settings
		    bAutoWidth     : false,
		    fnPreDrawCallback: function () {
		        // Initialize the responsive datatables helper once.
		        if (!responsiveHelper) {
		            responsiveHelper = new ResponsiveDatatablesHelper(tableContainer, breakpointDefinition);
		        }
		    },
		    fnRowCallback  : function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
		        responsiveHelper.createExpandIcon(nRow);
		    },
		    fnDrawCallback : function (oSettings) {
		        responsiveHelper.respond();
		    }
		});
		
		$(".dataTables_wrapper select").select2({
			minimumResultsForSearch: -1
		});
	});
</script>
	
			
		
	
	
	<link rel="stylesheet" href="{% static "Panel/js/dropzone/fileinput.js"%}">
	<link rel="stylesheet" href="{% static "Panel/js/dropzone/dropzone.css"%} ">
	<link rel="stylesheet" href="{% static "Panel/js/wysihtml5/bootstrap-wysihtml5.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/codemirror/lib/codemirror.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/uikit/css/uikit.min.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/uikit/addons/css/markdownarea.css" %}">
	<link rel="stylesheet" href="{% static "Panel/css/font-icons/font-awesome/css/font-awesome.min.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/datatables/responsive/css/datatables.responsive.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/select2/select2-bootstrap.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/select2/select2.css"%}">
	<script src="{% static "Panel/js/jquery.dataTables.min.js"%}"></script>
	<script src="{% static "Panel/js/datatables/TableTools.min.js"%}"></script>
	<script src="{% static "Panel/js/dataTables.bootstrap.js"%}"></script>
	<script src="{% static "Panel/js/datatables/jquery.dataTables.columnFilter.js"%}"></script>
	<script src="{% static "Panel/js/datatables/lodash.min.js"%}"></script>
	<script src="{% static "Panel/js/datatables/responsive/js/datatables.responsive.js"%}"></script>
	<script src="{% static "Panel/js/bootstrap.js"%}"></script>
	<script src="{% static "Panel/js/fileinput.js"%}"></script>
	<script src="{% static "Panel/js/select2/select2.min.js"%}"></script>
{% endblock %}

templates/blog/ver-noticias.html
{% extends 'app/panel.html'%}
 {% load staticfiles %}
 {% load widget_tweaks %}
 {% load blogtag %}
{% block tittle-view %}
<title>Gestión Post | Coreducar</title>
{% endblock %}
{% block titulo-view%}
<h3>Gestionar Posts del blog</h3>	
{% endblock %}
{% block body-view%} 
	<div class="col-sm-12">
		
		<a href="{% url 'crear_post' %}"><button class="pull-right btn btn-primary btn-flat btn-lg">Crear Nueva Publicación</button></a><br>
		
		<div class="col-sm-12">

			<div class="row">
				<div class="panel panel-primary" data-collapsed="0">
					
					<!-- panel head -->
					<div class="panel-heading">
						<div class="panel-title">Lista de Posts Creados</div>
						
						<div class="panel-options">
							
							<a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
							
						</div>
					</div>
					
					<!-- panel body -->
					<div class="panel-body">
						
						<table class="table table-bordered table-hover datatable" id="table-1">
							<thead>
								<tr>
									<th>#</th>
									<th>Nombre</th>
									<th>Slug</th>
									<th>Número de comentarios</th>
									<th>Opciones</th>
								</tr>
							</thead>
							<tbody>
								{% for post in posts %}
									<tr>
										<td>{{ forloop.counter }}</td>
										<td>{{post.titulo|truncatechars:50}}</td>
										<td>{{post.slug|truncatechars:30}}</td>
										<td>{{post.answer_set|get_count_comentarios}}</td>
										<td>
											<a href="/panel/blog/editar-post/{{post.id}}"><button class="btn">Editar</button></a>
											<a href="/panel/blog/borrar-post/{{post.id}}"><button class="btn">Borrar</button></a>
										</td>
									</tr>
								{% endfor %}
								
							</tbody>
							<tfoot>
								<tr>
									<th>#</th>
									<th>Nombre</th>
									<th>Slug</th>
									<th>Noticias relacionadas a esta Categoría</th>
									<th>Opciones</th>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	

<script type="text/javascript">
var responsiveHelper;
var breakpointDefinition = {
    tablet: 1024,
    phone : 480
};
var tableContainer;

	jQuery(document).ready(function($)
	{
		tableContainer = $("#table-1");
		
		tableContainer.dataTable({
			"sPaginationType": "bootstrap",
			"aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
			"bStateSave": true,
			

		    // Responsive Settings
		    bAutoWidth     : false,
		    fnPreDrawCallback: function () {
		        // Initialize the responsive datatables helper once.
		        if (!responsiveHelper) {
		            responsiveHelper = new ResponsiveDatatablesHelper(tableContainer, breakpointDefinition);
		        }
		    },
		    fnRowCallback  : function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
		        responsiveHelper.createExpandIcon(nRow);
		    },
		    fnDrawCallback : function (oSettings) {
		        responsiveHelper.respond();
		    }
		});
		
		$(".dataTables_wrapper select").select2({
			minimumResultsForSearch: -1
		});
	});
</script>
	
			
		
	
	
	<link rel="stylesheet" href="{% static "Panel/js/dropzone/fileinput.js"%}">
	<link rel="stylesheet" href="{% static "Panel/js/dropzone/dropzone.css"%} ">
	<link rel="stylesheet" href="{% static "Panel/js/wysihtml5/bootstrap-wysihtml5.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/codemirror/lib/codemirror.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/uikit/css/uikit.min.css" %}">
	<link rel="stylesheet" href="{% static "Panel/js/uikit/addons/css/markdownarea.css" %}">
	<link rel="stylesheet" href="{% static "Panel/css/font-icons/font-awesome/css/font-awesome.min.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/datatables/responsive/css/datatables.responsive.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/select2/select2-bootstrap.css"%}">
	<link rel="stylesheet" href="{% static "Panel/js/select2/select2.css"%}">
	<script src="{% static "Panel/js/jquery.dataTables.min.js"%}"></script>
	<script src="{% static "Panel/js/datatables/TableTools.min.js"%}"></script>
	<script src="{% static "Panel/js/dataTables.bootstrap.js"%}"></script>
	<script src="{% static "Panel/js/datatables/jquery.dataTables.columnFilter.js"%}"></script>
	<script src="{% static "Panel/js/datatables/lodash.min.js"%}"></script>
	<script src="{% static "Panel/js/datatables/responsive/js/datatables.responsive.js"%}"></script>
	<script src="{% static "Panel/js/bootstrap.js"%}"></script>
	<script src="{% static "Panel/js/fileinput.js"%}"></script>
	<script src="{% static "Panel/js/select2/select2.min.js"%}"></script>
{% endblock %}